
name: blue2th
description: A Bluetooth multi-connect audio app.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.5.0
  just_audio: ^0.9.34
  google_mobile_ads: ^3.0.0
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
  assets:
    - assets/
